FROM golang

ADD search-server /Go/src/github.com/ComputePractice2017/search-server 

RUN go get "github.com/gorilla/mux"
RUN go get "github.com/gorilla/handlers"
RUN go get "gopkg.in/gorethink/gorethink.v3"

RUN go install github.com/ComputePractice2017/search-server

ENTRYPOINT /Go/bin/search-server
ENV RETHINKDB_HOST db

EXPOSE 8000
